blank_issues_enabled: false
contact_links:
  - name: ‚ùì adri IDP Community Slack
    url: https://join.slack.com/t/adri-idp/shared_invite/zt-1pxtehxom-fCFtF9rRe3vFqUiFFeAkmg
    about: Please ask and answer questions here.
